# bootc-image-builder configuration for vSphere VMDK output
# Note: Filesystem type is set via --rootfs xfs flag, not here

[[customizations.user]]
name = "cloud-user"
groups = ["wheel"]
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDB8mc6fEmiRTeuV/gBkcCfSAj7rQ305d881ZNdHLl2+WVycAlcsSUnlt/T96AR5NeZUAR43n3vAL71EV7VKYB+8JAG75tjXrjvSP11cGt6DpoWEh9sy41qizQOoGjQmlTXqBNZyi0bDl1qIBfRSRAQcLGKwZiKxfgtxkxUgUIwyIKLaxC+KZT0Z95oQkM2yLcp7ETQYdVDneeD2ThlrEg464DYxHM6/vcGNKVZGEY8WAw6jHAp+Zf9LHHpIZp6ZRZ9FVCkdRpIsN5dS/naSnH2PgD47MOOzVkirkUcMcu4Gnpq2nuvv8tmAQVEaKWzh6zNjOZBLVhUzKjyS7IdpvCj tshefi@tshefi.tlv.csb"
